POST http://localhost:5230/api/Auth/token HTTP/1.1
content-type: application/json

{
  "username": "rostami.siavash@gmail.com",
  "password": "111111"
}

###

GET http://localhost:5230/api/Account/UserProfile
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoicm9zdGFtaS5zaWF2YXNoQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InJvc3RhbWkuc2lhdmFzaEBnbWFpbC5jb20iLCJzdWIiOiJyb3N0YW1pLnNpYXZhc2hAZ21haWwuY29tIiwianRpIjoiNTgxZjg2ODMtZTU4Mi00ZjliLWFjNDktODk5MWYwOThhM2U0IiwibmJmIjoxNjYxNzI3ODI4LCJleHAiOjE2NjY5MTE4MjgsImlzcyI6Im9yYXRpbyIsImF1ZCI6Im9yYXRpbyJ9.NOgdRgcGtvPb9cf4ml3kX6VScZEQLLHzTmyn7OiMG8E